---
- name: Create app directiory
  file:
    path: /home/ubuntu/app
    state: directory

- name: Extract files to remote (EC2 instance)
  unarchive:
    src: /home/circleci/project/artifact.tar.gz
    dest: /home/ubuntu/app

- name: "Start app"
  become: yes
  shell:  |
    npm install
    pm2 stop default
    pm2 start npm -- start